"""
GeoAI Schema Factory & Complete Coverage Generator
Dynamically creates canonical Pydantic schemas and Tool Registry entries for 100% of Groundhog & GeoCore functions.
"""
import os
import re
import json
import inspect
from typing import Dict, Any, ClassVar, Type, Optional, Tuple, List, Union
from pydantic import create_model, Field, AliasChoices

from core.geoai.schemas.base import GeoAIBaseModel
from core.geoai.units import clean_unit_label, get_unit_dimension
from core.geoai.schemas import SCHEMA_REGISTRY
from core.geoai.tool_registry import tool_registry, GeoAITool

# Load inventory metadata
_INVENTORY_PATH = os.path.join(os.path.dirname(__file__), 'parameter_inventory.json')
_INVENTORY_BY_FUNC: Dict[str, List[Dict[str, Any]]] = {}

if os.path.exists(_INVENTORY_PATH):
    try:
        with open(_INVENTORY_PATH, 'r', encoding='utf-8') as f:
            _inv_data = json.load(f)
            for item in _inv_data:
                _INVENTORY_BY_FUNC.setdefault(item['function_id'], []).append(item)
    except Exception:
        pass


def _map_python_type(type_str: str, param_name: str = "") -> Type:
    type_lower = (type_str or '').lower()
    p_lower = (param_name or '').lower()

    # 1. Parameter name-based heuristics for geotechnical objects and text fields
    if p_lower in ('soilprofile', 'soil_profile', 'profile', 'calculationgrid', 'grid', 'data', 'raw_data', 'object_id', 'obj_id', 'obj', 'object', 'dataframe', 'df', 'path', 'filepath', 'filename', 'file'):
        return Union[str, Dict[str, Any], List[Any], Any]

    # Categorical, enum, description, and classification fields
    if (
        p_lower.endswith('_col') or p_lower.endswith('_column') or p_lower.endswith('column') or
        p_lower.endswith('_description') or p_lower.endswith('description') or
        p_lower.endswith('_desc') or p_lower.endswith('desc') or
        p_lower.endswith('_category') or p_lower.endswith('category') or
        p_lower.endswith('_categories') or p_lower.endswith('categories') or
        p_lower.endswith('_type') or p_lower.endswith('type') or
        p_lower.endswith('_mode') or p_lower.endswith('mode') or
        p_lower.endswith('_method') or p_lower.endswith('method') or
        p_lower.endswith('_standard') or p_lower.endswith('standard') or
        p_lower.endswith('_theory') or p_lower.endswith('theory') or
        p_lower.endswith('_class') or p_lower.endswith('class') or
        p_lower in (
            'api_relativedensity', 'api_soildescription', 'soildescription',
            'relativedensity', 'classification', 'symbol', 'standard', 'method',
            'theory', 'material', 'consistency', 'density_class', 'sand_class',
            'shape', 'foundation_type', 'pile_type', 'installation_method',
            'failure_mode', 'loading_condition', 'drainage_condition', 'soil_behavior_type',
            'sbt', 'sbt_index', 'uscs', 'layer', 'stratum', 'geology', 'correlation',
            'soiltype', 'soiltypecolumn', 'depth_column', 'qc_column', 'rf_column',
            'fs_column', 'u2_column', 'u0_column', 'water_table_column', 'unit', 'name',
            'encoding', 'errors', 'title', 'legend', 'colormap', 'color', 'pattern',
            'layer_name', 'standard_type', 'design_approach', 'approach'
        )
    ):
        return Optional[Union[str, int, float, Any]]

    if p_lower in ('parameters', 'plot_parameters', 'properties', 'columns', 'correlations', 'selected_parameters', 'times', 'settlements', 'grainsize', 'pctpassing', 'depths', 'requested_depths'):
        return Union[List[str], List[float], List[Any], str, Any]

    if p_lower in ('fillcolordict', 'colordict', 'custom_colors', 'options', 'kwargs', 'overrides'):
        return Optional[Union[Dict[str, Any], str, Any]]

    # 2. Type string-based matching
    if 'int' in type_lower:
        return int
    elif 'bool' in type_lower:
        return bool
    elif 'str' in type_lower or 'string' in type_lower or 'text' in type_lower or 'path' in type_lower or 'select' in type_lower or 'enum' in type_lower:
        return Union[str, Any]
    elif 'list' in type_lower or 'array' in type_lower or 'tuple' in type_lower:
        return Union[List[float], List[str], List[Any], str, Any]
    elif 'dict' in type_lower or 'json' in type_lower or 'object' in type_lower or 'soilprofile' in type_lower or 'grid' in type_lower:
        return Union[Dict[str, Any], str, Any]
    elif 'any' in type_lower:
        return Any
    else:
        # Default numeric
        return float


class GeoAIAutoInputModel(GeoAIBaseModel):
    """
    Base for input schemas generated from Groundhog signatures.

    Inherits ``extra='forbid'`` from GeoAIBaseModel: unknown/misspelled keys are rejected
    (AGENTS.md §5, §7). Field units come from the Groundhog docstrings and are normalised
    deterministically by GeoAIBaseModel via core.geoai.units (§16).
    """
    geoai_autogenerated: ClassVar[bool] = True


_PARAM_LINE_RE = r'^\s*:param\s+{name}\s*:(.*)$'
_BRACKET_UNIT_RE = re.compile(r'\[\s*(?::math:`([^`]*)`|([^\[\]]*))\s*\]')


def _docstring_param_line(doc: str, p_name: str) -> Tuple[Optional[str], Optional[str]]:
    """Return (documented name, rest of line) for ``:param p_name:`` (case-insensitive)."""
    for flags in (re.M, re.M | re.I):
        m = re.search(_PARAM_LINE_RE.format(name=re.escape(p_name)), doc, flags)
        if m:
            documented = re.match(r'^\s*:param\s+(\S+?)\s*:', m.group(0)).group(1)
            return documented, m.group(1)
    return None, None


def resolve_parameter_unit(func_name: str, func_obj: Any, p_name: str) -> str:
    """
    Canonical unit of a Groundhog parameter ('-' when unitless/unknown).

    Source of truth is the Groundhog docstring (``:param x: ... [:math:`kPa`]``). The
    parameter inventory is only used when the docstring does not document the parameter,
    and then only if units.py recognises the unit (the inventory contains units that leaked
    from neighbouring docstring lines).
    """
    doc = getattr(func_obj, '__doc__', '') or ''
    _, line = _docstring_param_line(doc, p_name)
    if line is not None:
        m = _BRACKET_UNIT_RE.search(line)
        if not m:
            return '-'
        return clean_unit_label(m.group(1) if m.group(1) is not None else m.group(2))
    inv_p = next((p for p in _INVENTORY_BY_FUNC.get(func_name, []) if p['parameter_name'] == p_name), {})
    unit = clean_unit_label(inv_p.get('canonical_unit'))
    return unit if get_unit_dimension(unit) is not None else '-'


def build_schema_for_function(func_name: str, func_obj: Any) -> Type[GeoAIBaseModel]:
    """Dynamically generate a canonical Pydantic model for any function."""
    fields: Dict[str, Any] = {}
    inv_params = {p['parameter_name']: p for p in _INVENTORY_BY_FUNC.get(func_name, [])}
    doc_text = getattr(func_obj, '__doc__', '') or ''

    try:
        sig = inspect.signature(func_obj)
        parameters = sig.parameters
    except Exception:
        parameters = {}

    for p_name, param in parameters.items():
        if p_name in ('self', 'cls', 'args', 'kwargs'):
            continue

        inv_p = inv_params.get(p_name, {})
        py_type = _map_python_type(inv_p.get('python_type', ''), p_name)
        unit = resolve_parameter_unit(func_name, func_obj, p_name)
        desc = inv_p.get('physical_meaning', f"{p_name.replace('_', ' ').title()}")
        if unit != '-' and unit not in desc:
            desc = f"{desc} [{unit}]"
        documented_name, _ = _docstring_param_line(doc_text, p_name)
        
        # Determine default
        default_val = ...
        if param.default != inspect.Parameter.empty:
            default_val = param.default
            if isinstance(default_val, float) and (default_val != default_val):
                default_val = None
        elif inv_p.get('default_value'):
            default_val = inv_p.get('default_value')
            if default_val in ('null', 'nan', 'NaN'):
                default_val = None

        # Check docstring for options
        doc = getattr(func_obj, '__doc__', '') or ''
        if f":param {p_name}:" in doc and "Options:" in doc:
            py_type = Optional[Union[str, float, int, Any]] if default_val is not ... else Union[str, float, int, Any]
        elif isinstance(default_val, str) and py_type == float:
            py_type = Optional[Union[str, float, int, Any]]

        # Determine min / max bounds only for pure numeric types
        min_v = None
        max_v = None
        if py_type in (float, int, Optional[float], Optional[int]):
            try:
                min_v = float(inv_p['min_value']) if inv_p.get('min_value') != '' else None
            except (ValueError, TypeError):
                min_v = None
            try:
                max_v = float(inv_p['max_value']) if inv_p.get('max_value') != '' else None
            except (ValueError, TypeError):
                max_v = None

        field_kwargs = {
            "description": desc,
            "json_schema_extra": {"unit": unit}
        }
        if min_v is not None:
            field_kwargs["ge"] = min_v
        if max_v is not None:
            field_kwargs["le"] = max_v
        # Name documented with different case in the Groundhog docstring (e.g. ':param PI:'
        # for signature 'pi') is accepted as an alias; the canonical key stays the signature name.
        if documented_name and documented_name != p_name:
            field_kwargs["validation_alias"] = AliasChoices(p_name, documented_name)

        # Nullable support
        if inv_p.get('is_nullable') or default_val is None:
            py_type = Optional[py_type]

        fields[p_name] = (py_type, Field(default=default_val, **field_kwargs))

    model_name = f"{''.join(w.capitalize() for w in func_name.split('_'))}Input"

    # Strict (extra='forbid' inherited): unknown keys are rejected with a structured error
    # listing valid parameters (see core.geoai.validator.build_validation_error).
    dyn_model = create_model(
        model_name,
        __base__=GeoAIAutoInputModel,
        **fields
    )
    return dyn_model


def populate_full_coverage(registry_obj: Any):
    """
    Scans entire function_map and registers schemas and tools for 100% of functions.
    """
    for func_name, func_obj in registry_obj.function_map.items():
        # 1. Register in SCHEMA_REGISTRY if not already present
        if func_name not in SCHEMA_REGISTRY:
            try:
                dyn_input_model = build_schema_for_function(func_name, func_obj)
                SCHEMA_REGISTRY[func_name] = (dyn_input_model, None)
            except Exception as e:
                pass

        # 2. Register in Tool Registry if not already present
        if not tool_registry.get_tool(func_name):
            try:
                schema_pair = SCHEMA_REGISTRY.get(func_name)
                input_model = schema_pair[0] if schema_pair else build_schema_for_function(func_name, func_obj)
                output_model = schema_pair[1] if schema_pair else None
                
                module_name = getattr(func_obj, '__module__', 'groundhog')
                cat = module_name.split('.')[-1] if '.' in module_name else module_name
                doc = inspect.getdoc(func_obj) or f"Calculates {func_name.replace('_', ' ')} using Groundhog."
                # Extract first paragraph of docstring
                first_paragraph = doc.split('\n\n')[0].replace('\n', ' ').strip()

                tool = GeoAITool(
                    name=func_name,
                    description=first_paragraph,
                    category=cat,
                    input_model=input_model,
                    output_model=output_model,
                    func=func_obj
                )
                tool_registry._tools[func_name] = tool
            except Exception as e:
                pass
