/**
 * Author: Utkarsh Gupta
 * License: GPL v3
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import Papa from 'papaparse';
import logoFull from '../assets/logo-2.png';

const BRAND_NAME = "GeoCore";
const DISCLAIMER = "Disclaimer: This report was generated by GeoCore. The results should be verified by a qualified geotechnical engineer.";

// Helper to flatten object for CSV
const flattenObject = (obj) => {
    const flattened = {};
    Object.keys(obj).forEach((key) => {
        if (typeof obj[key] === 'object' && obj[key] !== null) {
            flattened[key] = JSON.stringify(obj[key]);
        } else {
            flattened[key] = obj[key];
        }
    });
    return flattened;
};

export const downloadJSON = (data, filename) => {
    const content = JSON.stringify(data, null, 2);
    const blob = new Blob([content], { type: 'application/json' });
    triggerDownload(blob, `${filename}.json`);
};

export const downloadCSV = (data, filename) => {
    // Flatten result if it was wrapped
    const displayData = data.result !== undefined ? data.result : data;

    let content = "";
    if (displayData.type === 'SoilProfile' && displayData.preview) {
        content = Papa.unparse(displayData.preview);
    } else if (displayData.type === 'CalculationGrid' || (displayData.nodes && displayData.elements)) {
        // For CalculationGrid, elements are usually the most relevant "tabular" data
        // If elements missing but nodes present, use nodes
        const tableData = (displayData.elements && displayData.elements.length > 0)
            ? displayData.elements
            : displayData.nodes;

        if (tableData && tableData.length > 0) {
            content = Papa.unparse(tableData);
        } else {
            // Fallback to simple object representation if no tables found
            const simpleData = Object.entries(displayData).reduce((acc, [k, v]) => {
                if (typeof v !== 'object' && k !== 'warnings') acc[k] = v;
                return acc;
            }, {});
            content = Papa.unparse([simpleData]);
        }
    } else if (displayData.raw_data) {
        // Handle result types that wrap their data (e.g. Plotly results)
        const raw = displayData.raw_data;

        // Detect if Columnar Data (Dict of Arrays)
        const keys = Object.keys(raw).filter(k => k !== 'warnings');
        const arrayKey = keys.find(k => Array.isArray(raw[k]));
        const isColumnar = !!arrayKey;

        if (isColumnar) {
            // Convert Columnar (Dict of Lists) to Row-based (List of Dicts)
            const length = raw[arrayKey].length;
            const rows = [];
            for (let i = 0; i < length; i++) {
                const row = {};
                keys.forEach(k => {
                    const val = raw[k];
                    // Handle case where some columns might be shorter or scalar
                    if (Array.isArray(val)) {
                        row[k] = val[i] !== undefined ? val[i] : '';
                    } else {
                        row[k] = val; // Repeat scalar for every row
                    }
                });
                rows.push(row);
            }
            content = Papa.unparse(rows);
        } else {
            // Single Object / Scalars
            // Use flattening to handle nested objects if any
            content = Papa.unparse([flattenObject(raw)]);
        }

    } else if (Array.isArray(displayData)) {
        content = Papa.unparse(displayData.map(flattenObject));
    } else if (typeof displayData === 'object' && displayData !== null) {
        // Single object fallback
        const simpleData = Object.entries(displayData).reduce((acc, [k, v]) => {
            // If value is simple, keep it.
            if (typeof v !== 'object' && k !== 'warnings') acc[k] = v;
            // If v is NOT an object (e.g. null), keep it? null is object.
            // typeof null is object.
            if (v === null) acc[k] = '';
            return acc;
        }, {});

        if (Object.keys(simpleData).length > 0) {
            content = Papa.unparse([simpleData]);
        } else {
            // Try to flatten the whole thing if simple extract failed
            content = Papa.unparse([flattenObject(displayData)]);
        }
    } else if (displayData.type === 'plotly' || displayData.type === 'plot' || displayData.type === 'multi_plot') {
        const plotData = displayData.data || [];
        if (Array.isArray(plotData) && plotData.length > 0) {
            // We want to create a CSV where each trace has its own X and Y columns
            // Series 1 X, Series 1 Y, Series 2 X, Series 2 Y ...
            const columns = {};
            let maxRows = 0;

            plotData.forEach((trace, index) => {
                const name = trace.name || `Series ${index + 1}`;
                const x = trace.x || [];
                const y = trace.y || [];
                maxRows = Math.max(maxRows, x.length, y.length);

                columns[`${name} (x)`] = x;
                columns[`${name} (y)`] = y;
            });

            const rows = [];
            for (let i = 0; i < maxRows; i++) {
                const row = {};
                Object.keys(columns).forEach(colName => {
                    const colData = columns[colName];
                    row[colName] = colData[i] !== undefined ? colData[i] : '';
                });
                rows.push(row);
            }
            content = Papa.unparse(rows);
        } else {
            // Fallback
            content = Papa.unparse([flattenObject(displayData)]);
        }
    } else {
        return;
    }

    const blob = new Blob([content], { type: 'text/csv' });
    triggerDownload(blob, `${filename}.csv`);
};

const PRIMARY_COLOR = [106, 142, 78]; // Brand Primary Blue
const SECONDARY_COLOR = [44, 62, 80]; // Dark Navy for contrast

export const generatePDF = async (results, inputs, functionName, filename, capturedImage = null, schema = null) => {
    console.log("generatePDF: Starting for", functionName);
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Load Logo
    try {
        const logoData = await new Promise((resolve, reject) => {
            const img = new Image();
            img.src = logoFull;
            img.onload = () => resolve(img);
            img.onerror = () => {
                console.warn("generatePDF: Logo failed to load");
                reject(new Error("Logo not found"));
            };
            // Safety timeout
            setTimeout(() => reject(new Error("Logo timeout")), 2000);
        });

        // Add Logo (adjust dimensions as needed, assuming specific aspect ratio or fitting)
        // logo-2.png
        const logoWidth = 40;
        const logoHeight = (logoData.height / logoData.width) * logoWidth;
        doc.addImage(logoData, 'PNG', 14, 10, logoWidth, logoHeight);

        // Adjust Y position based on logo height, but keep it tight
        var headerY = 10 + logoHeight + 10;

    } catch (e) {
        console.error("Failed to load logo for PDF", e);
        // Fallback to text
        doc.setFontSize(22);
        doc.setTextColor(44, 62, 80);
        doc.text(BRAND_NAME, 14, 20);
        var headerY = 30;
    }

    // Title (Geotechnical Analysis Report) - Left Aligned
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("Geotechnical Analysis Report", 14, headerY);

    // Date/Time - Right Aligned (Smaller Font)
    doc.setFontSize(9);
    const dateStr = new Date().toLocaleString();
    const dateWidth = doc.getTextWidth(dateStr);
    doc.text(dateStr, pageWidth - 14 - dateWidth, headerY);

    // Separator Line
    doc.setDrawColor(200);
    doc.line(14, headerY + 3, pageWidth - 14, headerY + 3);

    // 2. Metadata (Function Name)
    doc.setFontSize(11);
    doc.setTextColor(...PRIMARY_COLOR);
    doc.setFont(undefined, 'bold');
    doc.text("Function: ", 14, headerY + 10);

    const labelWidth = doc.getTextWidth("Function: ");
    doc.setTextColor(0);
    doc.setFont(undefined, 'normal');
    doc.text(functionName, 14 + labelWidth, headerY + 10);

    let finalY = headerY + 22;

    // 3. Inputs Section
    if (inputs && Object.keys(inputs).length > 0) {
        doc.setFillColor(...PRIMARY_COLOR);
        doc.rect(14, finalY - 5, pageWidth - 28, 8, 'F');
        doc.setFontSize(11);
        doc.setTextColor(255);
        doc.setFont(undefined, 'bold');
        doc.text("INPUT PARAMETERS", pageWidth / 2, finalY + 0.5, { align: 'center' });
        doc.setTextColor(0);
        doc.setFont(undefined, 'normal');

        finalY += 8;

        const inputRows = Object.entries(inputs).map(([k, v]) => {
            // Map key to schema title if available
            const label = (schema && schema.properties && schema.properties[k] && schema.properties[k].title)
                ? schema.properties[k].title
                : k;

            // Handle file objects or paths
            if (v instanceof File) return [label, v.name];
            if (typeof v === 'object' && v !== null) return [label, JSON.stringify(v)];
            return [label, String(v)];
        });

        autoTable(doc, {
            startY: finalY,
            head: [['Parameter', 'Value']],
            body: inputRows,
            theme: 'striped',
            headStyles: { fillColor: SECONDARY_COLOR, fontStyle: 'bold' },
            styles: { fontSize: 9, cellPadding: 3 },
            alternateRowStyles: { fillColor: [240, 244, 248] }
        });

        finalY = doc.lastAutoTable.finalY + 15;
    }

    // 4. Results Section
    if (finalY > 250) {
        doc.addPage();
        finalY = 20;
    }

    doc.setFillColor(...PRIMARY_COLOR);
    doc.rect(14, finalY - 5, pageWidth - 28, 8, 'F');
    doc.setFontSize(11);
    doc.setTextColor(255);
    doc.setFont(undefined, 'bold');
    doc.text("CALCULATION RESULTS", pageWidth / 2, finalY + 0.5, { align: 'center' });
    doc.setTextColor(0);
    doc.setFont(undefined, 'normal');

    finalY += 8;

    // Determine how to render results
    const displayData = results.result !== undefined ? results.result : results;

    if (displayData.type === 'SoilProfile' && displayData.preview) {
        // Render layers table
        const headers = Object.keys(displayData.preview[0]);
        const rows = displayData.preview.map(row => Object.values(row).map(v =>
            (typeof v === 'number') ? v.toFixed(3) : String(v)
        ));

        doc.setFontSize(11);
        doc.setFont(undefined, 'bold');
        doc.text("Soil Profile: ", 14, finalY + 5);
        const spLabelWidth = doc.getTextWidth("Soil Profile: ");
        doc.setFont(undefined, 'normal');
        doc.text(displayData.name || '', 14 + spLabelWidth, finalY + 5);

        autoTable(doc, {
            startY: finalY + 10,
            head: [headers],
            body: rows,
            theme: 'grid',
            headStyles: { fillColor: PRIMARY_COLOR },
            styles: { fontSize: 8 }
        });
    } else if (displayData.type === 'CalculationGrid' || (displayData.nodes && displayData.elements)) {
        doc.setFontSize(10);
        doc.text(`Grid Composition: ${displayData.nodes_count || displayData.nodes?.length || 0} Nodes | ${displayData.elements_count || displayData.elements?.length || 0} Elements`, 14, finalY + 5);
        doc.text(`Description: ${displayData.message || 'Numerical grid for calculation'}`, 14, finalY + 10);

        let currentY = finalY + 20;

        // Nodes Table
        if (displayData.nodes && displayData.nodes.length > 0) {
            doc.setFontSize(11);
            doc.setFont(undefined, 'bold');
            doc.text("Grid Nodes (Point Parameters)", 14, currentY);
            doc.setFont(undefined, 'normal');

            const nodeHeaders = Object.keys(displayData.nodes[0]);
            const nodeRows = displayData.nodes.map(row => Object.values(row).map(v =>
                (typeof v === 'number') ? v.toFixed(3) : String(v)
            ));

            autoTable(doc, {
                startY: currentY + 5,
                head: [nodeHeaders],
                body: nodeRows,
                theme: 'striped',
                headStyles: { fillColor: PRIMARY_COLOR, textColor: 255, fontStyle: 'bold' },
                styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' },
                alternateRowStyles: { fillColor: [245, 248, 250] },
                columnStyles: { 0: { fontStyle: 'bold' } }
            });
            currentY = doc.lastAutoTable.finalY + 15;
            finalY = currentY - 15;
        }

        // Elements Table
        if (displayData.elements && displayData.elements.length > 0) {
            if (currentY > 230) {
                doc.addPage();
                currentY = 20;
            }

            doc.setFontSize(11);
            doc.setFont(undefined, 'bold');
            doc.text("Grid Elements (Tributary Values)", 14, currentY);
            doc.setFont(undefined, 'normal');

            const elemHeaders = Object.keys(displayData.elements[0]);
            const elemRows = displayData.elements.map(row => Object.values(row).map(v =>
                (typeof v === 'number') ? v.toFixed(3) : String(v)
            ));

            autoTable(doc, {
                startY: currentY + 5,
                head: [elemHeaders],
                body: elemRows,
                theme: 'striped',
                headStyles: { fillColor: SECONDARY_COLOR, textColor: 255, fontStyle: 'bold' },
                styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' },
                alternateRowStyles: { fillColor: [250, 245, 252] },
                columnStyles: { 0: { fontStyle: 'bold' } }
            });
            finalY = doc.lastAutoTable.finalY + 15;
        }
    } else if (displayData.type === 'plotly' || displayData.type === 'plot' || displayData.type === 'multi_plot' || displayData.type === 'image' || capturedImage) {
        // Render captured visualization (Plotly or Static Image)
        if (finalY > 240) {
            doc.addPage();
            finalY = 20;
        }
        doc.setFontSize(11);
        doc.text("Visualization Plot", 14, finalY + 5);

        if (capturedImage) {
            // Add the image
            const imgWidth = pageWidth - 28;
            try {
                // Approximate aspect ratio for Plotly (approx 16:9 or similar)
                // If we want to be exact we could pass height from App.jsx, 
                // but 0 in doc.addImage often auto-fits.
                doc.addImage(capturedImage, 'PNG', 14, finalY + 10, imgWidth, 0);

                // Helper to estimate height added by image (since doc.lastAutoTable doesn't apply)
                // We'll estimate based on a standard Plotly aspect ratio if height is 0
                // Or just assume a fixed buffer
                finalY += 100;
            } catch (e) {
                console.error("Failed to add captured image to PDF", e);
                doc.setFontSize(10);
                doc.setTextColor(255, 0, 0);
                doc.text("[Error: Could not render plot image]", 14, finalY + 10);
                doc.setTextColor(0);
                finalY += 20;
            }
        } else {
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text("[Note: Visualization snapshot was not available for this report]", 14, finalY + 12);
            doc.setTextColor(0);
            finalY += 20;
        }
    } else if (typeof displayData === 'object' && !displayData.image && !displayData.type) {
        // Helper to format values for PDF (truncate large arrays/objects)
        const formatValueForPDF = (value) => {
            if (Array.isArray(value)) {
                // Join array elements to allow text wrapping in PDF table cell
                return `[${value.length} items]: ${value.join(', ')}`;
            }
            if (typeof value === 'object' && value !== null) {
                const keys = Object.keys(value);
                if (keys.length > 5) {
                    return `{Object(${keys.length}): ${keys.slice(0, 3).join(', ')} ...}`;
                }
                return JSON.stringify(value);
            }
            return String(value);
        };

        const resultRows = Object.entries(displayData).map(([k, v]) => {
            if (k === 'warnings') return null;
            return [k, formatValueForPDF(v)];
        }).filter(Boolean);

        autoTable(doc, {
            startY: finalY,
            head: [['Result Parameter', 'Value']],
            body: resultRows,
            theme: 'striped',
            headStyles: { fillColor: SECONDARY_COLOR },
            columnStyles: {
                0: { cellWidth: 60, fontStyle: 'bold' },
                1: { cellWidth: 'auto', overflow: 'linebreak' }
            }
        });
    } else {
        // Fallback text
        doc.setFontSize(10);
        const text = JSON.stringify(displayData, null, 2);
        const splitText = doc.splitTextToSize(text, pageWidth - 28);
        doc.text(splitText, 14, finalY + 5);
    }

    // Warnings
    const warnings = results.warnings || (results.result && results.result.warnings) || [];
    if (warnings.length > 0) {
        let warnY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : finalY + 50;
        doc.setTextColor(230, 126, 34); // Orange
        doc.setFontSize(12);
        doc.text("Warnings:", 14, warnY);
        doc.setFontSize(10);
        warnings.forEach((w, i) => {
            doc.text(`- ${w}`, 14, warnY + 6 + (i * 5));
        });
    }

    // 5. Footer / Disclaimer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(DISCLAIMER, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
        console.log("generatePDF: Page numbers added");
    }

    console.log("generatePDF: Triggering save for", `${filename}.pdf`);
    doc.save(`${filename}.pdf`);
    console.log("generatePDF: Save called successfully");
};

const triggerDownload = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};
