/**
 * Author: Utkarsh Gupta
 * License: GPL v3
 *
 * The app's view of the GeoCore standard quantity directory (src/config/quantityStandard.json, a copy of
 * python-backend/core/quantity_standard.json generated by `python -m core.quantity_directory`):
 * one symbol, name and unit per physical quantity, and one spelling per unit.
 */
import standard from '../config/quantityStandard.json';
import functionUnits from '../config/quantityFunctionUnits.json';
import functionOverrides from '../config/quantityFunctionOverrides.json';

const normUnit = (text) => String(text ?? '')
    .trim()
    .toLowerCase()
    .replace(/^:math:`(.*)`$/, '$1')
    .replace(/\s*\/\s*/g, '/')
    .replace(/³/g, '3')
    .replace(/²/g, '2')
    .replace(/⁴/g, '4');

const normKey = (text) => String(text ?? '').replace(/[\s_-]+/g, '').toLowerCase();

const unitIndex = new Map();
Object.entries(standard.unit_aliases).forEach(([canonical, spellings]) => {
    unitIndex.set(normUnit(canonical), canonical);
    spellings.forEach((spelling) => unitIndex.set(normUnit(spelling), canonical));
});

const exactIndex = new Map();
const looseIndex = new Map(); // null marks a loose key shared by two quantities (qt / Qt): exact match only
standard.quantities.forEach((q) => {
    q.keys.forEach((key) => {
        if (!exactIndex.has(key)) exactIndex.set(key, q);
        const nk = normKey(key);
        looseIndex.set(nk, !looseIndex.has(nk) || looseIndex.get(nk) === q ? q : null);
    });
});

/** Standard spelling of a unit ("pct" -> "%", "kN/m3" -> "kN/m³"); unknown units are returned trimmed. */
export function canonicalUnit(raw) {
    if (raw == null) return '';
    return unitIndex.get(normUnit(raw)) ?? String(raw).replace(/^[[(]|[\])]$/g, '').trim();
}

const bareKey = (key) => String(key).replace(/\s*\[[^\]]*\]\s*$/, '').trim();
const quantityById = new Map(standard.quantities.map((q) => [q.id, q]));

/**
 * Standard quantity for a parameter / output name (a trailing "[unit]" is ignored), or null.
 * Pass the function id to honour per-function re-mappings (e.g. "Ic" in the inertia function).
 */
export function getQuantity(key, functionId) {
    if (!key) return null;
    const bare = bareKey(key);
    const remap = functionId && functionOverrides.quantity.find((o) => o.function === functionId && o.key === bare);
    if (remap) return quantityById.get(remap.quantity) ?? null;
    return exactIndex.get(bare) ?? looseIndex.get(normKey(bare)) ?? null;
}

/**
 * Unit to show for a function's parameter / output. The function's own documented unit always wins
 * (an explicit "[unit]" in the output key, or the schema's unit); then a unit recorded from its docstring
 * that differs from the standard; then the standard unit. Returns '' when nothing is known: no unit is invented.
 */
export function unitFor(functionId, key, documentedUnit) {
    if (documentedUnit != null && String(documentedUnit).trim() !== '') return canonicalUnit(documentedUnit);
    const embedded = /\[([^\]]*)\]\s*$/.exec(String(key ?? ''));
    if (embedded) return canonicalUnit(embedded[1]);
    const recorded = functionUnits.units?.[functionId]?.[bareKey(key)];
    if (recorded) return recorded;
    return getQuantity(key, functionId)?.unit ?? '';
}

export const QUANTITY_CATEGORIES = [...new Set(standard.quantities.map((q) => q.category))];
export const QUANTITIES = standard.quantities;
