"""
Docs pipeline for the GeoCore website: website/_content -> website/docs.

Input (generated by website/_content/extract_docs.py, treated as read-only):
  _content/nav.json              {home:{title,slug}, sections:[{title,slug,children?}]}
  _content/pages/<slug>.md       YAML front-matter + Markdown
  _content/groundhog/assets/**   figures, served at /docs/assets/groundhog/**

Output:
  docs/<slug>/index.html         one page per slug (URL /docs/<slug>/); slug "index" -> docs/index.html
  docs/assets/groundhog/**       mirrored figures
  docs/search-index.json         written by build.py from search_entries()

Math: $...$ and $$...$$ are stashed before Markdown and restored as \\(...\\) / \\[...\\] for the vendored
KaTeX auto-render (assets/js/math.js), so Markdown never touches LaTeX.

Author: Utkarsh Gupta
License: GPL v3
"""
from __future__ import annotations

import html
import json
import re
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import markdown
import yaml

CONTENT_DIRNAME = "_content"
REQUIRED_FIELDS = ("title", "slug", "section", "description", "origin", "source_url", "license",
                   "author", "attribution", "groundhog_version", "edited_by_geocore")

# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def slug_url(slug: str) -> str:
    """Site-root-relative URL for a docs slug."""
    return "docs/" if slug == "index" else f"docs/{slug}/"


def groundhog_source_ref(content_dir: Path) -> str:
    """Git ref every upstream link must use: the commit (or tag) of the groundhog GeoCore ships,
    recorded by the extractor in groundhog/api.json."""
    api = json.loads((content_dir / "groundhog" / "api.json").read_text(encoding="utf-8"))
    return api.get("source_ref") or f"v{api['groundhog_version']}"


def load_nav(content_dir: Path) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    import json
    data = json.loads((content_dir / "nav.json").read_text(encoding="utf-8"))

    def convert(node: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "title": node["title"],
            "slug": node["slug"].replace("/", "-"),
            "content_slug": node["slug"],
            "url": slug_url(node["slug"]),
            "children": [convert(c) for c in node.get("children", [])],
        }

    return data["home"], [convert(s) for s in data["sections"]]


def load_page(path: Path) -> Tuple[Dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path}: missing front-matter")
    _, fm, body = text.split("---", 2)
    meta = yaml.safe_load(fm) or {}
    missing = [f for f in REQUIRED_FIELDS if f not in meta]
    if missing:
        raise ValueError(f"{path}: front-matter missing {missing}")
    return meta, body.lstrip("\n")


# ---------------------------------------------------------------------------
# Markdown with protected math
# ---------------------------------------------------------------------------

_FENCE_OPEN = re.compile(r"^[ ]{0,3}(?P<fence>`{3,}|~{3,})[ ]*[\w#.+-]*[ ]*(\{[^\n]*\})?[ ]*$")
_INLINE = re.compile(
    r"(?P<code>(?P<ticks>`+)(?:(?!(?P=ticks)).)+?(?P=ticks))"
    r"|\$\$(?P<disp>.+?)\$\$"
    r"|(?<![\\$])\$(?P<inl>[^$\n]+?)\$",
    re.S,
)


def _stash_math(body: str) -> Tuple[str, List[Tuple[str, str]]]:
    """Replace math with alphanumeric tokens outside fenced code and code spans."""
    stash: List[Tuple[str, str]] = []
    out: List[str] = []
    chunk: List[str] = []

    def flush() -> None:
        if not chunk:
            return
        text = "".join(chunk)
        chunk.clear()

        def repl(m: "re.Match[str]") -> str:
            if m.group("code"):
                return m.group(0)
            kind, tex = ("display", m.group("disp")) if m.group("disp") is not None else ("inline", m.group("inl"))
            stash.append((kind, tex.strip()))
            return f"GCMATH{len(stash) - 1}X"

        out.append(_INLINE.sub(repl, text))

    fence: Optional[str] = None
    for line in body.splitlines(keepends=True):
        stripped = line.rstrip("\n")
        if fence is None:
            m = _FENCE_OPEN.match(stripped)
            if m:
                flush()
                fence = m.group("fence")
                out.append(line)
            else:
                chunk.append(line)
        else:
            out.append(line)
            s = stripped.strip()
            if s and set(s) == {fence[0]} and len(s) >= len(fence):
                fence = None
    flush()
    return "".join(out), stash


def _sphinx_compat(kind: str, tex_src: str) -> str:
    """Sphinx wraps display math containing '&' or '\\\\' in a split environment; KaTeX needs it explicit."""
    if kind == "display" and ("&" in tex_src or "\\\\" in tex_src) and "\\begin{" not in tex_src:
        return "\\begin{aligned}" + tex_src + "\\end{aligned}"
    return tex_src


def _restore_math(html_text: str, stash: List[Tuple[str, str]]) -> str:
    def tex(i: int) -> str:
        return html.escape(_sphinx_compat(*stash[i]), quote=False)

    def block(m: "re.Match[str]") -> str:
        i = int(m.group(1))
        if stash[i][0] == "display":
            return f'<div class="math-display">\\[{tex(i)}\\]</div>'
        return m.group(0)

    html_text = re.sub(r"<p>\s*GCMATH(\d+)X\s*</p>", block, html_text)

    def inline(m: "re.Match[str]") -> str:
        i = int(m.group(1))
        if stash[i][0] == "display":
            return f'<span class="math-display-inline">\\[{tex(i)}\\]</span>'
        return f'<span class="math">\\({tex(i)}\\)</span>'

    return re.sub(r"GCMATH(\d+)X", inline, html_text)


def _plain_math(text: str, stash: List[Tuple[str, str]]) -> str:
    return re.sub(r"GCMATH(\d+)X", lambda m: stash[int(m.group(1))][1], text)


def make_markdown() -> markdown.Markdown:
    return markdown.Markdown(
        extensions=["tables", "fenced_code", "codehilite", "toc", "attr_list", "md_in_html", "sane_lists"],
        extension_configs={
            "codehilite": {"css_class": "highlight", "guess_lang": False, "use_pygments": True},
            "toc": {"permalink": False, "toc_depth": "2-3"},
        },
        output_format="html",
    )


def render_markdown(md: markdown.Markdown, body: str) -> Tuple[str, List[Dict[str, Any]], bool]:
    """Return (html, toc tokens flattened, has_math)."""
    md.reset()
    text, stash = _stash_math(body)
    out = md.convert(text)
    out = _restore_math(out, stash)
    toc: List[Dict[str, Any]] = []

    def walk(tokens: List[Dict[str, Any]]) -> None:
        for t in tokens:
            name = html.unescape(re.sub(r"<[^>]+>", "", t.get("name", "")))
            toc.append({"id": t["id"], "title": _plain_math(name, stash), "level": t["level"]})
            walk(t.get("children", []))

    walk(getattr(md, "toc_tokens", []))
    # Prefer the explicit <a id="..."></a> anchors that precede API headings (stable, documented ids).
    explicit = dict((h, a) for a, h in re.findall(r'<a id="([^"]+)"></a>\s*(?:</p>)?\s*<h[23] id="([^"]+)"', out))
    for t in toc:
        t["id"] = explicit.get(t["id"], t["id"])
    return out, toc, bool(stash)


# ---------------------------------------------------------------------------
# Link rewriting and checks
# ---------------------------------------------------------------------------

_DOCS_LINK = re.compile(r'(href|src)="/docs/([^"#?]*)([#?][^"]*)?"')


def rewrite_links(page_html: str, known_slugs: set, asset_root: Path, problems: List[str], where: str) -> str:
    """/docs/<slug> -> /docs/<slug>/ (pretty URL); verify slugs and image files exist."""
    def repl(m: "re.Match[str]") -> str:
        attr, path, tail = m.group(1), m.group(2), m.group(3) or ""
        if path.startswith("assets/groundhog/"):
            if not (asset_root / path[len("assets/groundhog/"):]).is_file():
                problems.append(f"{where}: missing image /docs/{path}")
            return f'{attr}="/docs/{path}{tail}"'
        slug = path.rstrip("/") or "index"
        if slug not in known_slugs:
            problems.append(f"{where}: link to unknown page /docs/{path}")
            return m.group(0)
        return f'{attr}="/{slug_url(slug)}{tail}"'

    return _DOCS_LINK.sub(repl, page_html)


_EXT_IMG = re.compile(r'<img\b[^>]*\bsrc="(https?://[^"]+)"[^>]*>')


def _external_image(m: "re.Match[str]") -> str:
    """Third-party images (e.g. PyPI/Binder badges) would break the CSP and leak visits; show their alt text."""
    alt = re.search(r'\balt="([^"]*)"', m.group(0))
    label = (alt.group(1) if alt else "") or "external image"
    return f'<span class="ext-img" title="{html.escape(m.group(1))}">{label}</span>'


def decorate_html(page_html: str) -> str:
    """Replace external images, wrap tables for horizontal scrolling and make images lazy."""
    page_html = _EXT_IMG.sub(_external_image, page_html)
    page_html = re.sub(r"<table>", '<div class="table-wrap"><table class="data">', page_html)
    page_html = page_html.replace("</table>", "</table></div>")
    page_html = re.sub(r"<img (?![^>]*loading=)", '<img loading="lazy" decoding="async" ', page_html)
    return page_html


def plain_text(page_html: str) -> str:
    text = re.sub(r"<(pre|script|style)\b.*?</\1>", " ", page_html, flags=re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    text = re.sub(r"\\[()\[\]]", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def inline_title(title: str) -> Tuple[str, str]:
    """Front-matter titles may contain Markdown code spans (```groundhog```). Return (text, html)."""
    text = re.sub(r"`+([^`]+?)`+", r"\1", title)
    parts = re.split(r"`+([^`]+?)`+", title)
    out = []
    for i, p in enumerate(parts):
        out.append(f"<code>{html.escape(p)}</code>" if i % 2 else html.escape(p))
    return text, "".join(out)


# ---------------------------------------------------------------------------
# Images
# ---------------------------------------------------------------------------


def mirror_assets(src: Path, dst: Path) -> Tuple[int, int]:
    """Copy src tree to dst, skipping unchanged files and removing stale ones. Returns (files, bytes)."""
    count = size = 0
    seen = set()
    if src.is_dir():
        for f in src.rglob("*"):
            if not f.is_file():
                continue
            rel = f.relative_to(src)
            target = dst / rel
            seen.add(target)
            st = f.stat()
            count += 1
            size += st.st_size
            if target.exists() and target.stat().st_size == st.st_size and target.stat().st_mtime >= st.st_mtime:
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, target)
    if dst.is_dir():
        for f in sorted(dst.rglob("*"), reverse=True):
            if f.is_file() and f not in seen:
                f.unlink()
            elif f.is_dir() and not any(f.iterdir()):
                f.rmdir()
    return count, size


# ---------------------------------------------------------------------------
# Build all pages
# ---------------------------------------------------------------------------


def build_pages(content_dir: Path, website: Path, problems: List[str]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Any]]:
    """Return (docs_nav, pages, home_page). Pages are dicts following the docs page contract."""
    home, nav = load_nav(content_dir)
    source_ref = groundhog_source_ref(content_dir)
    pages_dir = content_dir / "pages"
    asset_src = content_dir / "groundhog" / "assets"
    known = {p.relative_to(pages_dir).with_suffix("").as_posix() for p in pages_dir.rglob("*.md")}

    nav_slugs = {home["slug"]}

    def collect(nodes: List[Dict[str, Any]]) -> None:
        for n in nodes:
            nav_slugs.add(n["content_slug"])
            collect(n["children"])
    collect(nav)
    for s in sorted(known - nav_slugs):
        problems.append(f"page not in nav: {s}")
    for s in sorted(nav_slugs - known):
        problems.append(f"nav entry without page: {s}")

    md = make_markdown()
    pages: List[Dict[str, Any]] = []
    home_page: Dict[str, Any] = {}
    for slug in sorted(known):
        meta, body = load_page(pages_dir / f"{slug}.md")
        if meta["slug"] != slug:
            problems.append(f"{slug}: front-matter slug is {meta['slug']!r}")
        body_html, toc, has_math = render_markdown(md, body)
        body_html = rewrite_links(body_html, known, asset_src, problems, slug)
        body_html = decorate_html(body_html)
        title_text, title_html = inline_title(str(meta["title"]))
        if meta.get("origin") == "groundhog" and f"/{source_ref}/" not in str(meta.get("source_url", "")) \
                and "/tree/" not in str(meta.get("source_url", "")):
            problems.append(f"{slug}: source_url not pinned to {source_ref}")
        toc_full = toc
        # Long API pages: keep the right-hand TOC readable (h2 only when there are many entries).
        if len(toc) > 40:
            toc = [t for t in toc if t["level"] == 2]
        upstream = meta.get("upstream_docs_urls") or ([meta["upstream_docs_url"]] if meta.get("upstream_docs_url") else [])
        page = {
            "slug": slug,
            "title": title_text,
            "title_html": title_html,
            "description": meta.get("description"),
            "url": slug_url(slug),
            "body_html": body_html,
            "toc": toc,
            "toc_full": toc_full,
            "has_math": has_math,
            "meta": {
                "section": meta.get("section"),
                "origin": meta.get("origin"),
                "author": meta.get("author"),
                "license": meta.get("license"),
                "attribution": meta.get("attribution"),
                "source_url": meta.get("source_url"),
                "groundhog_version": meta.get("groundhog_version"),
                "edited_by_geocore": bool(meta.get("edited_by_geocore")),
                "edit_note": meta.get("geocore_edit_note"),
                "upstream_docs_urls": upstream,
                "module": meta.get("module"),
                "geocore_available": meta.get("geocore_available"),
                "geocore_functions": meta.get("geocore_functions") or [],
                "notebook": meta.get("notebook"),
                "sources": meta.get("sources") or [],
            },
            "plain": plain_text(body_html),
        }
        if slug == home["slug"]:
            home_page = page
        else:
            pages.append(page)

    count, size = mirror_assets(asset_src, website / "docs" / "assets" / "groundhog")
    home_page.setdefault("stats", {})
    home_page["stats"] = {"images": count, "image_bytes": size}
    return nav, pages, home_page


def search_entries(pages: List[Dict[str, Any]], body_chars: int = 600) -> List[Dict[str, Any]]:
    """One entry per page, plus one per h2/h3 anchor on API reference pages (function/class names)."""
    entries: List[Dict[str, Any]] = []
    for p in pages:
        summary = p["description"] or ""
        entries.append({
            "id": "doc-" + p["slug"].replace("/", "-"),
            "title": p["title"],
            "url": p["url"],
            "section": p["meta"]["section"] or "Docs",
            "summary": summary,
            "headings": [t["title"] for t in p["toc"]][:30],
            "body": p["plain"][:body_chars],
        })
        if p["meta"].get("module"):
            for t in p["toc_full"]:
                name = t["title"].replace("class ", "").strip()
                entries.append({
                    "id": f"api-{p['slug'].replace('/', '-')}-{t['id']}",
                    "title": name,
                    "url": f"{p['url']}#{t['id']}",
                    "section": p["meta"]["module"],
                    "summary": "",
                    "headings": [],
                    "body": "",
                })
    return entries
