"""
Auto-schema bounds come from Groundhog's own validation (AGENTS.md §6, §7, §16).

- parameter_inventory.json bounds equal Groundhog's @Validator ranges wherever both exist
  (regenerate with ``python -m core.geoai.inventory_sync``);
- realistic engineering values validate (e.g. su in kPa is not capped at 1 kPa);
- every Groundhog function in the registry is exposed as a tool (or skipped with a reason);
- optional parameters whose Groundhog default is NaN are omitted from the call when unset.
"""
import inspect
import math

import pytest

from core.registry import registry
import core.geoai.tool_definitions  # noqa: F401
from core.geoai.exceptions import GeoAIValidationError
from core.geoai.inventory_sync import groundhog_validation_spec, resolve_groundhog_object
from core.geoai.schema_factory import MODEL_EXCLUDED_FUNCTIONS, SKIPPED_FUNCTIONS, _INVENTORY_BY_FUNC
from core.geoai.schemas import SCHEMA_REGISTRY
from core.geoai.tool_registry import tool_registry
from core.geoai.units import UnitDimension, get_unit_dimension


def _bound(v):
    return None if v == "" or v is None else float(v)


def _specs():
    for name, obj in registry.function_map.items():
        spec = groundhog_validation_spec(obj)
        if spec:
            yield name, obj, spec


def test_inventory_bounds_equal_groundhog_validation_ranges():
    drift = []
    for name, _, spec in _specs():
        for row in _INVENTORY_BY_FUNC.get(name, []):
            s = spec.get(row["parameter_name"])
            if not s or s.get("type") not in ("float", "int"):
                continue
            inv = (_bound(row["min_value"]), _bound(row["max_value"]))
            gh = (_bound(s.get("min_value")), _bound(s.get("max_value")))
            if inv != gh:
                drift.append(f"{name}.{row['parameter_name']}: inventory {inv} != Groundhog {gh}")
    assert not drift, "Run `python -m core.geoai.inventory_sync`:\n" + "\n".join(drift)


def test_schema_bounds_equal_groundhog_validation_ranges():
    drift = []
    for name, _, spec in _specs():
        tool = tool_registry.get_tool(name)
        if tool is None or not getattr(tool.input_model, "geoai_autogenerated", False):
            continue
        for field, fi in tool.input_model.model_fields.items():
            s = spec.get(field)
            if not s or s.get("type") not in ("float", "int"):
                continue
            ge = next((m.ge for m in fi.metadata if hasattr(m, "ge")), None)
            le = next((m.le for m in fi.metadata if hasattr(m, "le")), None)
            gh = (_bound(s.get("min_value")), _bound(s.get("max_value")))
            if (ge, le) != gh:
                drift.append(f"{name}.{field}: schema {(ge, le)} != Groundhog {gh}")
    assert not drift, "\n".join(drift)


# Upper bounds below these values would reject everyday engineering inputs.
_MIN_PLAUSIBLE_UPPER = {
    UnitDimension.PRESSURE: 10.0,       # kPa (Groundhog calibration ranges can be as low as 10 kPa)
    UnitDimension.UNIT_WEIGHT: 10.0,    # kN/m3 (submerged unit weights reach ~12)
    UnitDimension.ANGLE: 10.0,          # deg
    UnitDimension.LENGTH: 0.001,        # m (Hazen D10 is capped at 2 mm by Groundhog)
}


def _to_canonical(value, unit):
    from core.geoai.units import convert_unit
    base = {UnitDimension.PRESSURE: "kPa", UnitDimension.UNIT_WEIGHT: "kN/m3",
            UnitDimension.ANGLE: "deg", UnitDimension.LENGTH: "m"}
    return convert_unit(value, unit, base[get_unit_dimension(unit)])


def test_no_implausible_upper_bounds_on_auto_schemas():
    problems = []
    for name, tool in tool_registry._tools.items():
        if not getattr(tool.input_model, "geoai_autogenerated", False):
            continue
        for field, fi in tool.input_model.model_fields.items():
            unit = (fi.json_schema_extra or {}).get("unit", "-")
            dim = get_unit_dimension(unit) if unit != "-" else None
            le = next((m.le for m in fi.metadata if hasattr(m, "le")), None)
            if dim in _MIN_PLAUSIBLE_UPPER and le is not None and \
                    _to_canonical(le, unit) < _MIN_PLAUSIBLE_UPPER[dim]:
                problems.append(f"{name}.{field}: upper bound {le} {unit}")
    assert not problems, "\n".join(problems)


@pytest.mark.parametrize("tool,args", [
    ("API_unit_end_bearing_clay", {"undrained_shear_strength": 150.0}),
    ("API_unit_shaft_friction_clay", {"undrained_shear_strength": 75.0, "sigma_vo_eff": 120.0}),
    ("su_categories", {"undrained_shear_strength": 500.0}),
    ("cycliccontours_dssclay_andersen", {"undrained_shear_strength": 50.0, "average_shear_stress": 10.0,
                                         "cyclic_shear_stress": 20.0}),
])
def test_realistic_su_values_validate(tool, args):
    tool_registry.get_tool(tool).input_model(**args)


def test_out_of_groundhog_range_is_a_clear_validation_error():
    # Groundhog's Andersen contours are calibrated for 1 <= su <= 100 kPa (it returns NaN outside).
    with pytest.raises(GeoAIValidationError, match="undrained_shear_strength"):
        tool_registry.invoke_tool("cycliccontours_dssclay_andersen",
                                  {"undrained_shear_strength": 200.0, "average_shear_stress": 10.0,
                                   "cyclic_shear_stress": 20.0})


def test_every_groundhog_function_is_exposed_or_excluded_with_reason():
    missing = [n for n in registry.function_map
               if n not in tool_registry._tools and n not in SKIPPED_FUNCTIONS and n not in MODEL_EXCLUDED_FUNCTIONS]
    assert not missing
    assert not SKIPPED_FUNCTIONS, SKIPPED_FUNCTIONS
    # Every function has an input schema (UI form validation), exposed to the model or not.
    assert all(n in SCHEMA_REGISTRY for n in registry.function_map)
    for name in ("stresses_lineload_retainingwall", "stresses_stripload_retainingwall", "piletest_chinkondler",
                 "pilegroupeffect_reesevanimpe", "reinforced_circularsection_inertia",
                 "bendingstiffness_soilmix_method1", "bendingstiffness_soilmix_method2"):
        assert tool_registry.get_tool(name) is not None, name


def test_previously_unregistered_function_matches_groundhog():
    args = dict(imposedstress=50.0, width=2.0, offset=1.0, toe_depth=5.0, depth=2.0)
    res = tool_registry.invoke_tool("stresses_stripload_retainingwall", args)
    res.pop("_provenance")
    direct = resolve_groundhog_object(registry.function_map["stresses_stripload_retainingwall"])(**args)
    assert res.keys() == direct.keys()
    for k, v in direct.items():
        if isinstance(v, float):
            assert res[k] == pytest.approx(v, rel=1e-12, nan_ok=True)
    model = tool_registry.get_tool("pilegroupeffect_reesevanimpe").input_model
    assert "List" in str(model.model_fields["pile_y"].annotation)


# ---------------------------------------------------------------- NaN defaults
_SPT = dict(N=20, borehole_diameter=100.0, rod_length=10.0, country="United States",
            hammertype="Safety", hammerrelease="Rope and pulley")


def test_nan_default_parameters_are_omitted_when_unset():
    fn = resolve_groundhog_object(registry.function_map["spt_N60_correction"])
    nan_params = [p for p, v in inspect.signature(fn).parameters.items()
                  if isinstance(v.default, float) and math.isnan(v.default)]
    assert nan_params == ["eta_H", "eta_B", "eta_S", "eta_R"]
    model = tool_registry.get_tool("spt_N60_correction").input_model
    assert model.geoai_omit_when_none == frozenset(nan_params)
    assert not set(nan_params) & set(model(**_SPT).geoai_call_kwargs())

    res = tool_registry.invoke_tool("spt_N60_correction", dict(_SPT))
    res.pop("_provenance")
    direct = fn(**_SPT)
    assert res == direct and res["N60 [-]"] == pytest.approx(20.0)
    # Forwarding None (the old behaviour) makes Groundhog return NaN for everything.
    assert math.isnan(fn(**_SPT, eta_H=None)["N60 [-]"])


def test_nan_default_parameter_still_accepts_explicit_value():
    fn = resolve_groundhog_object(registry.function_map["spt_N60_correction"])
    res = tool_registry.invoke_tool("spt_N60_correction", dict(_SPT, eta_H=55.0))
    res.pop("_provenance")
    assert res == fn(**_SPT, eta_H=55.0)
    res_null = tool_registry.invoke_tool("spt_N60_correction", dict(_SPT, eta_H="n/a"))
    res_null.pop("_provenance")
    assert res_null == fn(**_SPT)
