"""
Strict tool schemas & deterministic unit normalisation (AGENTS.md §5, §7, §16, §17, §25).

- Unknown keys are rejected with a structured, recoverable error.
- Documented aliases are still accepted.
- Unit strings are converted by core.geoai.units for auto-registered Groundhog tools.
- Every tool's input fields match the parameters of the callable it invokes.
- Results for correct inputs equal direct Groundhog calls (deterministic oracle).
"""
import importlib
import inspect
import math

import pytest

from core.registry import registry  # noqa: F401  (populates auto-registered Groundhog tools)
import core.geoai.tool_definitions  # noqa: F401  (registers curated tools)
from core.geoai.exceptions import GeoAIUnitError, GeoAIValidationError
from core.geoai.schemas.shallowfoundations import ShallowFoundationCapacityUndrainedInput
from core.geoai.tool_registry import tool_registry
from core.geoai.units import convert_unit, normalize_parameter_value
from core.geoai.validator import validate_and_coerce_inputs


def _invoke(tool, **args):
    res = tool_registry.invoke_tool(tool, args)
    res.pop("_provenance", None)
    return res


def _groundhog(tool_name):
    """Resolve the real Groundhog function behind a tool (independent of the registry)."""
    target = tool_registry.get_tool(tool_name).target_callable()
    resolved = target.resolve() if hasattr(target, "resolve") else target
    return getattr(importlib.import_module(resolved.__module__), resolved.__name__)


def _assert_same_result(actual, expected):
    assert set(expected) <= set(actual)
    for k, v in expected.items():
        if isinstance(v, float) and math.isnan(v):
            assert math.isnan(actual[k])
        elif isinstance(v, (int, float)) and not isinstance(v, bool):
            assert actual[k] == pytest.approx(v, rel=1e-12), k
        else:
            assert actual[k] == v, k


def _auto(tool_name):
    tool = tool_registry.get_tool(tool_name)
    assert tool is not None and getattr(tool.input_model, "geoai_autogenerated", False)
    return tool


# ---------------------------------------------------------------- unknown keys
def test_unknown_key_rejected_on_auto_tool_with_valid_names():
    _auto("nq_frictionangle_sand")
    with pytest.raises(GeoAIValidationError) as exc:
        tool_registry.invoke_tool("nq_frictionangle_sand", {"friction_angle": 32, "bogus": 3})
    err = exc.value
    assert "unknown parameter(s) 'bogus'" in err.message
    assert "Valid parameters: friction_angle" in err.message
    detail = next(d for d in err.errors if d["type"] == "unknown_parameter")
    assert detail["field"] == "bogus" and detail["valid_parameters"] == ["friction_angle"]
    assert err.to_dict()["status"] == "ValidationError"


def test_misspelled_key_gets_suggestion_and_missing_field_reported():
    with pytest.raises(GeoAIValidationError) as exc:
        tool_registry.invoke_tool("nq_frictionangle_sand", {"friction_angl": 32})
    err = exc.value
    assert "did you mean 'friction_angle'" in err.message
    types = {d["type"] for d in err.errors}
    assert {"unknown_parameter", "missing"} <= types


def test_unknown_key_rejected_on_curated_tool():
    with pytest.raises(GeoAIValidationError, match="unknown parameter"):
        tool_registry.invoke_tool("calculate_relative_density",
                                  {"void_ratio": 0.6, "e_min": 0.4, "e_max": 0.9, "density": 1})


def test_curated_aliases_still_accepted():
    ref = _invoke("calculate_relative_density", void_ratio=0.6, e_min=0.4, e_max=0.9)
    for key in ("voidratio", "e"):
        assert _invoke("calculate_relative_density", **{key: 0.6, "emin": 0.4, "emax": 0.9}) == ref


def test_auto_alias_from_docstring_name_case():
    # Groundhog documents ':param PI:' for the signature parameter 'pi'.
    args = dict(strain=0.01, sigma_m_eff=100.0)
    assert _invoke("modulusreduction_plasticity_ishibashi", PI=20.0, **args) == \
        _invoke("modulusreduction_plasticity_ishibashi", pi=20.0, **args)


def test_json_schema_offered_to_model_is_strict_with_clean_units():
    schema = next(t for t in tool_registry.list_tools() if t["name"] == "nq_frictionangle_sand")["input_schema"]
    assert schema["additionalProperties"] is False
    prop = schema["properties"]["friction_angle"]
    assert prop["unit"] == "deg" and prop["type"] == "number"


def test_ui_path_keeps_legacy_passthrough_for_auto_schemas():
    # core.registry special cases read extra keys (e.g. 'nan_strategy'); the UI path keeps them.
    validated, _ = validate_and_coerce_inputs("nq_frictionangle_sand", {"friction_angle": "32", "ui_hint": "x"})
    assert validated["friction_angle"] == 32.0 and validated["ui_hint"] == "x"
    with pytest.raises(GeoAIValidationError, match="unknown parameter"):
        validate_and_coerce_inputs("calculate_relative_density", {"void_ratio": 0.6, "e_min": 0.4,
                                                                  "e_max": 0.9, "bogus": 1})


# ---------------------------------------------------------------- unit conversion (auto tools)
def test_angle_radians_converted_to_degrees():
    rad = math.radians(32.0)
    assert _invoke("nq_frictionangle_sand", friction_angle=f"{rad} rad") == \
        pytest.approx(_invoke("nq_frictionangle_sand", friction_angle=32.0))
    assert _invoke("nq_frictionangle_sand", friction_angle="32°") == _invoke("nq_frictionangle_sand", friction_angle=32.0)


def test_pressure_converted_to_kpa():
    direct = _groundhog("overburdencorrection_spt_liaowhitman")(N=20, sigma_vo_eff=150.0)
    res = _invoke("overburdencorrection_spt_liaowhitman", N=20, sigma_vo_eff="0.15 MPa")
    _assert_same_result(res, direct)
    res_psf = _invoke("overburdencorrection_spt_liaowhitman", N=20, sigma_vo_eff="3000 psf")
    kpa = convert_unit(3000, "psf", "kPa")
    _assert_same_result(res_psf, _groundhog("overburdencorrection_spt_liaowhitman")(N=20, sigma_vo_eff=kpa))


def test_unit_weight_converted_to_kn_per_m3():
    kn = convert_unit(120.0, "pcf", "kN/m3")
    direct = _groundhog("dryunitweight_watercontent")(watercontent=0.2, bulkunitweight=kn)
    _assert_same_result(_invoke("dryunitweight_watercontent", watercontent=0.2, bulkunitweight="120 pcf"), direct)
    _assert_same_result(_invoke("dryunitweight_watercontent", watercontent=0.2, bulkunitweight=f"{kn} kN/m³"), direct)


def test_length_converted_to_metres():
    direct = _groundhog("stresses_stripload")(z=5.0, x=0.5, width=2.0, imposedstress=100.0)
    res = _invoke("stresses_stripload", z="5000 mm", x="50 cm", width="2 m", imposedstress="0.1 MPa")
    _assert_same_result(res, direct)


@pytest.mark.parametrize("tool,args,bad", [
    ("nq_frictionangle_sand", {"friction_angle": "30 kPa"}, "friction_angle"),
    ("dryunitweight_watercontent", {"watercontent": 0.2, "bulkunitweight": "19 kPa"}, "bulkunitweight"),
    ("stresses_stripload", {"z": "5 kN", "x": 0.0, "width": 2.0, "imposedstress": 100.0}, "z"),
    ("overburdencorrection_spt_liaowhitman", {"N": 20, "sigma_vo_eff": "100 kN/m3"}, "sigma_vo_eff"),
])
def test_dimension_mismatch_rejected(tool, args, bad):
    with pytest.raises(GeoAIUnitError) as exc:
        tool_registry.invoke_tool(tool, args)
    assert "Unit dimension mismatch" in str(exc.value)
    assert exc.value.errors[0]["field"] == bad and exc.value.errors[0]["type"] == "unit_dimension_mismatch"


def test_dimensionless_field_rejects_physical_unit():
    with pytest.raises(GeoAIUnitError, match="dimensionless"):
        tool_registry.invoke_tool("dryunitweight_watercontent", {"watercontent": "20 kPa", "bulkunitweight": 19.0})


# ---------------------------------------------------------------- percent / fraction rule
def test_percent_to_fraction_for_dimensionless_field():
    direct = _groundhog("dryunitweight_watercontent")(watercontent=0.25, bulkunitweight=19.0)
    _assert_same_result(_invoke("dryunitweight_watercontent", watercontent="25 %", bulkunitweight=19.0), direct)
    _assert_same_result(_invoke("dryunitweight_watercontent", watercontent=0.25, bulkunitweight=19.0), direct)


def test_percent_field_accepts_fraction_with_unit_and_bare_percent():
    # 'strain' is documented in pct; bare numbers are taken as percent (never guessed).
    base = dict(pi=20.0, sigma_m_eff=100.0)
    ref = _invoke("modulusreduction_plasticity_ishibashi", strain=0.1, **base)
    assert _invoke("modulusreduction_plasticity_ishibashi", strain="0.1 %", **base) == ref
    assert _invoke("modulusreduction_plasticity_ishibashi", strain="0.001 fraction", **base) == pytest.approx(ref)


def test_units_percent_rules():
    assert normalize_parameter_value("25 %", expected_unit="-") == pytest.approx(0.25)
    assert normalize_parameter_value("0.25 ratio", expected_unit="-") == pytest.approx(0.25)
    assert normalize_parameter_value(0.25, expected_unit="-") == 0.25
    assert normalize_parameter_value("25 %", expected_unit="pct") == pytest.approx(25.0)
    assert normalize_parameter_value("0.25 fraction", expected_unit="%") == pytest.approx(25.0)
    assert normalize_parameter_value(0.25, expected_unit="pct") == 0.25
    assert convert_unit(0.5, "ratio", "-") == pytest.approx(0.5)
    assert convert_unit(0.5, "-", "ratio") == pytest.approx(0.5)
    with pytest.raises(GeoAIUnitError):
        normalize_parameter_value("5 blows", expected_unit="-", field_name="N")


def test_units_outside_taxonomy_accept_only_identical_unit():
    assert normalize_parameter_value("2 kPa/m", expected_unit="kPa/m") == 2.0
    assert normalize_parameter_value(2, expected_unit="kPa/m") == 2
    with pytest.raises(GeoAIUnitError, match="cannot be converted automatically"):
        normalize_parameter_value("2 MPa/m", expected_unit="kPa/m", field_name="su_increase")
    inst = ShallowFoundationCapacityUndrainedInput(width=2.0, unit_weight="18 kN/m3", su_base="0.05 MPa",
                                                   su_increase="1.5 kPa/m")
    assert (inst.su_base, inst.su_increase) == (pytest.approx(50.0), 1.5)


def test_units_strip_sphinx_markup_and_superscripts():
    assert normalize_parameter_value("1.5 MPa", expected_unit=":math:`kPa`") == pytest.approx(1500.0)
    assert normalize_parameter_value("18 kN/m³", expected_unit="kN/m3") == pytest.approx(18.0)


# ---------------------------------------------------------------- signature match (all tools)
def _named_params(sig):
    return {n: p for n, p in sig.parameters.items()
            if p.kind not in (p.VAR_KEYWORD, p.VAR_POSITIONAL) and n not in ("self", "cls")}


def test_every_tool_schema_matches_the_callable_it_invokes():
    problems = []
    for name, tool in tool_registry._tools.items():
        target = tool.target_callable()
        try:
            sig = inspect.signature(target)
        except (TypeError, ValueError):
            problems.append(f"{name}: no inspectable signature")
            continue
        params = _named_params(sig)
        fields = tool.input_model.model_fields
        if fields and not params:
            problems.append(f"{name}: invokes a **kwargs-only callable; use groundhog_forwarder()")
            continue
        for field in fields:
            if field not in params:
                problems.append(f"{name}: field '{field}' is not a parameter of {getattr(target, '__name__', target)}")
        for pname, p in params.items():
            if p.default is inspect.Parameter.empty and pname not in fields:
                problems.append(f"{name}: required parameter '{pname}' has no schema field")
        accepted = tool.input_model.geoai_accepted_keys()
        for key, field in accepted.items():
            if key in fields and key != field:
                problems.append(f"{name}: alias '{key}' of '{field}' shadows another field")
    assert not problems, "\n".join(problems)


# ---------------------------------------------------------------- results unchanged for correct inputs
@pytest.mark.parametrize("tool,args", [
    ("nq_frictionangle_sand", {"friction_angle": 32.0}),
    ("ngamma_frictionangle_vesic", {"friction_angle": 30.0}),
    ("k0_frictionangle_mesri", {"phi_cs": 30.0, "ocr": 2.0}),
    ("stresses_stripload", {"z": 3.0, "x": 0.5, "width": 2.0, "imposedstress": 150.0}),
    ("consolidationsettlement_mv", {"initial_height": 4.0, "effective_stress_increase": 80.0, "compressibility": 0.0003}),
    ("primaryconsolidationsettlement_nc", {"initial_height": 5.0, "initial_voidratio": 1.2, "initial_effective_stress": 60.0,
                                           "effective_stress_increase": 40.0, "compression_index": 0.4}),
    ("porosity_voidratio", {"voidratio": 0.7}),
    ("dryunitweight_watercontent", {"watercontent": 0.3, "bulkunitweight": 18.5}),
    ("relative_density", {"void_ratio": 0.6, "e_min": 0.4, "e_max": 0.9}),
    ("gmax_shearwavevelocity", {"Vs": 200.0, "gamma": 19.0}),
])
def test_registry_results_equal_direct_groundhog_calls(tool, args):
    direct = _groundhog(tool)(**args)
    output_model = tool_registry.get_tool(tool).output_model
    if output_model is not None:  # mirror GeoAITool.invoke: output model when it fits, else raw dict
        try:
            direct = output_model(**direct).model_dump()
        except Exception:
            pass
    _assert_same_result(_invoke(tool, **args), direct)
